### ISSUE TITLE
puppet-newrelic breaks with newest puppetlabs-apt

### ISSUE THREAD

**Issue by gytisgreitai** [fsalum/puppet-newrelic#32]
It seems that puppetlabs-apt was changed, so that apt::source no longer supports key_source parameter, but rather expects key to be a hash which has key_source property. 
See: https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/source.pp

Commit: https://github.com/puppetlabs/puppetlabs-apt/commit/ea4f615735d5fb6bb6b0fcbd735da76e0bb45c06

**Comment by DmitryINdig0** [comment]
up

**Comment by fsalum** [comment]
module 4.1.0 released on forge fixes this issue.
