### ISSUE TITLE
Invalid parameter options on Apt_key[Add key: B60A3EC9BC013B9C23790EC8B31B29E5548C16BF from Apt::Source newrelic]

### ISSUE THREAD

**Issue by bhechinger** [fsalum/puppet-newrelic#39]
I've upgraded all the other modules so that I can use puppetlabs/apt 2.1.0

I've upgraded your newrelic module to 4.1.1

Now I get this:

```
root@puppet1:~# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter options on Apt_key[Add key: B60A3EC9BC013B9C23790EC8B31B29E5548C16BF from Apt::Source newrelic] at /etc/puppetlabs/puppet/environments/production/modules/apt/manifests/key.pp:84 on node puppet1.4amlunch.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
root@puppet1:~#
```

**Comment by bhechinger** [comment]
Hmmm, jfryman/nginx now throws the same error. Maybe this is a problem with puppetlabs/apt?

**Comment by raoulbhatia** [comment]
I had a similar issue after upgrading various puppet modules,
but with the apt::backports class and not this one.

A restart of the puppet master resolved the issue for me.

Maybe this would be worth a shot?

**Comment by Zlo** [comment]
@raoulhatla Thanks, that fixed things here for me.

**Comment by confiq** [comment]
I'm using puppetlabs/apt 2.2.2. Now it throws this warning:

`Warning: Scope(Apt::Key[Add key: B60A3EC9BC013B9C23790EC8B31B29E5548C16BF from Apt::Source newrelic]): $key_source is deprecated and will be removed in the next major release. Please use $source instead.`


The source of this warning is here:
https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/key.pp#L31

I guess, you should simply use `$source` instead

**Comment by YarNhoj** [comment]
This should have been taken care of with PR #44.
