### ISSUE TITLE
Module not compatible with future parser

### ISSUE THREAD

**Issue by djimbel** [fsalum/puppet-newrelic#46]
Hi,

I was trying to use the future parser with the modules and doesn't work correctly.

The variable $newrelic_ini_appname (among others) has to be passed to the class ::newrelic::php::newrelic_ini from ::newrelic::agent::php if not newrelic.ini file content is not correct.

Regards,

**Comment by kariboe** [comment]
Is there any progress on this issue? Is there a way I can help?

**Comment by djimbel** [comment]
Hi,

I didn't have time to look at it, but i think moving the block

file { "${name}/newrelic.ini":
    path    => "${name}/newrelic.ini",
    content => template('newrelic/newrelic.ini.erb'),
    require => Exec["/usr/bin/newrelic-install ${name}"],
  }

from php/newrelic_ini.pp to agent/php.pp it will work.
