### ISSUE TITLE
Removing Approved Status

### ISSUE THREAD

**Issue by davinhanlon** [fsalum/puppet-newrelic#82]
Hi @fsalum -- this module is currently on the Puppet Forge as an "Approved" module. Do you intend to maintain this module? If not, we are going to remove the Approved banner as it is over two year's since it was updated. Thanks, Davin.

**Comment by davinhanlon** [comment]
Hi @fsalum - we're going to remove the Approved banner on the Forge for this module as it's been two years' since a release... please contact me if this is going to be an issue for you. Thanks!

**Comment by fsalum** [comment]
Hi @davinhanlon, sorry I have no time to dedicate to this module. If somebody else want to take over I can add to the repository.

**Comment by davinhanlon** [comment]
Thanks @fsalum. We'll remove the Approved label. If more contributors come forward that wish to take ownership and update the module we can review this decision. Thanks.
